export default {
  module: "calls",
  title: "Calls Analytics",
  subtitle: "Connection quality, talk time and agent throughput",
  businessTypeMode: "team",
  kpis: [
    { key: "total", label: "Total Calls", fmt: "int" },
    { key: "connected", label: "Connected", fmt: "int", drill: { field: "status", op: "in", value: ["connected", "completed"], label: "Connected" } },
    { key: "missed", label: "Missed / No-Answer", fmt: "int", positiveWhenDown: true, drill: { field: "status", op: "in", value: ["no-answer", "busy"], label: "Missed" } },
    { key: "failed", label: "Failed", fmt: "int", positiveWhenDown: true, drill: { field: "status", op: "eq", value: "failed", label: "Failed" } },
    { key: "avgDuration", label: "Avg Duration", fmt: "sec" },
    { key: "talk", label: "Total Talk Time", fmt: "sec" },
    { key: "uniqueLeads", label: "Unique Leads Called", fmt: "int" },
    { key: "voicemail", label: "Voicemail", fmt: "int", positiveWhenDown: true, drill: { field: "status", op: "eq", value: "voicemail", label: "Voicemail" } },
  ],
  ratios: [
    { key: "connectRate", label: "Connect rate" },
    { key: "missRate", label: "Miss rate", positiveWhenDown: true },
    { key: "avgHandleTime", label: "Avg handle time", fmt: "sec" },
    { key: "callsPerLead", label: "Calls per lead", fmt: "num" },
  ],
  charts: [
    { key: "trend", title: "Call Volume — Connected vs Missed", kind: "line", span: 2 },
    { key: "byStatus", title: "Calls by Status", kind: "bar", onSegmentDrill: (i, label) => ({ field: "status", op: "eq", value: label, label: `Status: ${label}` }) },
    { key: "byDirection", title: "Calls by Direction", kind: "donut", onSegmentDrill: (i, label) => ({ field: "direction", op: "eq", value: label, label: `Direction: ${label}` }) },
    { key: "byAgent", title: "Calls by Agent", kind: "bar", onSegmentDrill: (i, label) => ({ field: "agentName", op: "eq", value: label, label: `Agent: ${label}` }) },
    { key: "byHour", title: "Calls by Hour of Day", kind: "bar" },
  ],
  funnel: {
    title: "Call Funnel",
    stages: [
      { key: "dialed", label: "Dialed" },
      { key: "ringing", label: "Ringing" },
      { key: "connected", label: "Connected", drill: { field: "status", op: "in", value: ["connected", "completed"], label: "Connected" } },
      { key: "completed", label: "Completed", drill: { field: "status", op: "eq", value: "completed", label: "Completed" } },
    ],
  },
  table: {
    mode: "server",
    columns: [
      { key: "contactName", label: "Contact", type: "text" },
      { key: "phone", label: "Phone", type: "text" },
      { key: "agentName", label: "Agent", type: "text" },
      { key: "direction", label: "Direction", type: "badge" },
      { key: "status", label: "Status", type: "badge" },
      { key: "duration", label: "Duration (s)", type: "number" },
      { key: "disposition", label: "Disposition", type: "text" },
      { key: "team", label: "Team", type: "text", defaultHidden: true },
      { key: "created", label: "When", type: "date" },
    ],
    rowActions: { view: true, edit: false, delete: false },
  },
  filterDrawer: [
    { key: "direction", label: "Direction", kind: "multiselect", options: ["Outbound", "Inbound"] },
    { key: "status", label: "Status", kind: "multiselect", options: "@statuses" },
    { key: "agent", label: "Agent", kind: "multiselect", options: "@agents" },
    { key: "disposition", label: "Disposition", kind: "multiselect", options: "@dispositions" },
  ],
};
